### ISSUE TITLE
Recursive dependency

### ISSUE THREAD

**Issue by eserte** [stevieb9/p5-test-brewbuild#60]
Test::BrewBuild and Test::BrewBuild::Plugin::TestAgainst form a recursive dependency. This may cause a CPAN.pm install to fail:
```
Running make for S/ST/STEVEB/Test-BrewBuild-Plugin-TestAgainst-0.05.tar.gz
----       Unsatisfied dependencies detected during       ----
---- STEVEB/Test-BrewBuild-Plugin-TestAgainst-0.05.tar.gz ----
    Test::BrewBuild [requires]

Recursive dependency detected:
    Test::BrewBuild (have: 0.02; want: 1.04)
 => STEVEB/Test-BrewBuild-1.04.tar.gz
 => Test::BrewBuild::Plugin::TestAgainst (have: 0.03; requires: 0.05)
 => STEVEB/Test-BrewBuild-Plugin-TestAgainst-0.05.tar.gz
 => Test::BrewBuild (have: 0.02; requires: 1.04).
Cannot resolve.
```

**Comment by stevieb9** [comment]
Thank you very much for this. In fact, Test::BrewBuild isn't even required in that module, so I'll remove it from the PREREQ_PM.

Cheers!

**Comment by stevieb9** [comment]
Fixed in https://github.com/stevieb9/p5-test-brewbuild-plugin-testagainst/commit/8863a7b2fbddf8c0d30d2473a8c3f43c8d6deea4 (I mistyped the auto-close link in the commit)
